typography_spectrum: 0.5211838854562565
color:
  brandStrength: 0.9581133454494031
  lightness: 0.814873843414082
  saturation: 0.4514469867277116
  rhythmicContrast: 0.9133029732225223
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
github: true
layout_spectrum: 0.3711303832404094
name: chrisandreou
url: 'http://chrisandreou.innersummit.co.uk'
title: chrisandreou
content: []
description: leadership is still about how we connect with one another
