layout_spectrum: 0.6024890718211668
typography_spectrum: 0.6985413201601419
color:
  brandStrength: 0.13668531310938226
  lightness: 0.9271621964326
  saturation: 0.6718839508313502
  rhythmicContrast: 0.8642791746183308
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
github: true
name: chrisandreou
url: 'http://chrisandreou.innersummit.co.uk'
navigation:
  - name: Test
    id: fcca6c0d-b578-4578-9994-8fc80226e295
    type: content
  - name: Blog
    id: 85715f17-e620-4b79-b800-0f1cbe35a0c9
    type: content
title: chrisandreou
content: []
description: leadership is still about how we connect with one another
purpose:
  - type: external
    url: 'http://www.innersummit.co.uk'
    label: Resources
  - type: external
    url: 'http://www.innersummit.co.uk/about-us-2/innersummit/'
    label: 'Innersummit '
