typography_spectrum: 0.5211838854562565
color:
  brandStrength: 0.9581133454494031
  lightness: 0.814873843414082
  saturation: 0.4514469867277116
  rhythmicContrast: 0.9133029732225223
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
github: true
layout_spectrum: 0.3711303832404094
name: chrisandreou
url: 'http://chrisandreou.innersummit.co.uk'
navigation:
  - name: Blog
    id: 85715f17-e620-4b79-b800-0f1cbe35a0c9
    type: content
  - name: Test
    id: fcca6c0d-b578-4578-9994-8fc80226e295
    type: content
title: chrisandreou
content: []
description: leadership is still about how we connect with one another
purpose:
  - type: external
    url: 'http://www.innersummit.co.uk'
    label: Resources
  - type: external
    url: 'http://www.innersummit.co.uk/about-us-2/innersummit/'
    label: 'Innersummit '
