typography_spectrum: 0.6920766033823279
color:
  brandStrength: 0.5162799422706634
  lightness: 0.8852132851877572
  saturation: 0.6673769479865522
  rhythmicContrast: 0.8272117441721113
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
github: true
layout_spectrum: 0.0672492867579112
name: chrisandreou
url: 'http://chrisandreou.innersummit.co.uk'
navigation:
  - name: blog
    id: f755dce4-c61a-4863-8feb-c3e8d2b895b8
    type: content
  - name: Who We Are
    id: bff503d7-4047-4e30-ae20-4c6d31393c11
    type: content
  - name: Events
    id: 9749a748-1bed-40b3-9bb1-1dad908a1832
    type: content
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Leadership is still about connecting one with another
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FiuSpYv0R3Mc%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DiuSpYv0R3Mc&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FiuSpYv0R3Mc%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      datePublished: null
      isBasedOnUrl: 'https://youtu.be/iuSpYv0R3Mc'
      keywords: []
      related: []
      author:
        - name: Innersummit Ltd
          url: 'https://www.youtube.com/channel/UChJQzSmZYeQsrqTq5Mb3rgg'
          avatar: {}
      '@context': 'http://schema.org'
      title: Interactive
      '@type': VideoObject
      app_links: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://www.youtube.com/favicon.ico'
        domain: youtu.be
      description: This video is about Interactive
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: An Innersummit Group Presence
purpose:
  - url: 'http://www.innersummit.co.uk/lets-talk/'
    type: external
    label: Let's Talk
  - url: 'http://www.innersummit.co.uk'
    type: external
    label: The Innersummit Group
